### ISSUE TITLE
tests fails with swedish as system language

### ISSUE THREAD

**Issue by jakoblindqvist** [elastisys/scale.commons#2]
#### com.elastisys.scale.commons.util.countries.TestCountries.countryExistsRecognizesAllExistingCountries
fails when the locale is set to swedish.

#### com.elastisys.scale.commons.util.countries.TestCountries.countryExistsCaseInsensitive
fails when the locale is set to swedish.

**Comment by petergardfjall** [comment]
By setting swedish language via `export LANGUAGE=sv_SE` I was able to reproduce the problem.
Commit d6f7a84 resolves the issue.
